name: Split Learning
server:
  num-round: 1
  clients:
    - 1
    - 1
  model: YOLO11n

rabbit:
  address: 172.18.0.2
  username: user
  password: password

model:
  model_path: ./yolo11n.pt
  cut_layer: 
    - 10
    - 10
    - 10

  hybrid_training: False
  output_model: ./merged_model.pt

dataset:
  dataset_path:
    - ./datasets/livingroom_4_1.yaml
    - ./datasets/livingroom_3_2.yaml
    - ./datasets/livingroom_3_3.yaml

  concatenate_datasets: False

log_path: .

learning:
  learning-rate: 0.0001
  epochs: 1
  momentum: 0.5
  batch-size: 16
  control-count: 3
