name: Split Learning
server:
  num-round: 1
  clients:
    - 1
    - 1
  model: YOLO11n
  parameters:
    load: True
    save: True
  validation: True

rabbit:
  address: 127.0.0.1
  username: user
  password: password

model:
  model_path: ./yolo11n.pt
  cut_layer: 4

dataset:
  dataset_path: ./datasets/coco128.yaml

log_path: .

learning:
  learning-rate: 0.0001
  epoch: 5
  momentum: 0.5
  batch-size: 16
  control-count: 3
