name: Split Learning
server:
  num-round: 1
  clients:
    - 2
    - 1
  model: YOLO11n
  parameters:
    load: True
    save: True
  validation: True

rabbit:
  address: 127.0.0.1
  username: user
  password: password

model:
  model_path: ./yolo11n.pt
  cut_layer: 10
  output_model: ./merged_model.pt

dataset:
  dataset_path:
    - ./datasets/livingroom_2_1.yaml
    - ./datasets/livingroom_2_2.yaml

log_path: .

learning:
  learning-rate: 0.0001
  epochs: 20
  momentum: 0.5
  batch-size: 16
  control-count: 3
