name: Split Learning
server:
  num-round: 1
  clients:
    - 2
    - 1

rabbit:
  address: 172.18.0.2
  username: user
  password: password

model:
  task: detect
  load_partial_model: True
  model_path:
    - ./yolo11n.pt
  model_path_partial:
    - ./yolo11n_custom.yaml
    - ./yolo11n_custom.yaml
  cut_layer: 
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
    - 10
  hybrid_training: False
  valid_epoch_model: False
  output_model: ./merged_model.pt

dataset:
  dataset_path:
    - ./datasets/livingroom_4_1.yaml
    - ./datasets/livingroom_4_2.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC3.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC4.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC5.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC6.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC7.yaml
    - ./datasets/VOC_clients_client8_alpha01/VOC8.yaml
  concatenate_datasets: False
  iid_datasets: False

log_path: .

learning:
  learning-rate: 0.0001
  epochs: 4
  momentum: 0.5
  batch-size: 8
  control-count: 3
  worker: 0
