name: Split Learning
server:
  num-round: 1
  clients:
    - 2
    - 1

rabbit:
  address: 172.18.0.2
  username: user
  password: password

model:
  model_path: ./yolo11n.pt
  task: SEGMENT
  cut_layer: 
    - 5
    - 5
  hybrid_training: False
  valid_epoch_model: False
  output_model: ./merged_model.pt

dataset:
  dataset_path:
    - ./datasets/mnist160_ver2_1
    - ./datasets/mnist160_ver2_2
  concatenate_datasets: False
  iid_datasets: False

log_path: .

learning:
  learning-rate: 0.0001
  epochs: 100
  momentum: 0.5
  batch-size: 8
  control-count: 3
  worker: 4
