name: Split Learning
server:
  num-round: 1
  clients:
    - 1
    - 1
  model: YOLO11n
  parameters:
    load: True
    save: True
  validation: True

rabbit:
  address: 172.18.0.2
  username: user
  password: password

model:
  model_path: ./yolo11n.pt
  cut_layer: 1
  output_model: ./merged_model.pt

dataset:
  dataset_path:
    - ./datasets/livingroom_2.yaml
    - ./datasets/livingroom_2_for.yaml

log_path: .

learning:
  learning-rate: 0.0001
  epochs: 5
  momentum: 0.5
  batch-size: 16
  control-count: 3
