version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  server:
    container_name: split_learning_server
    build:
      context: . 
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "server.py"]
    
volumes:
  rabbitmq_data:
    driver: local