# Dùng image gốc của Ultralytics
FROM ultralytics/ultralytics:latest

# Đảm bảo pip được cập nhật
RUN pip install --upgrade pip

RUN pip install \
    requests==2.32.3 \
    pika==1.3.2

CMD ["bash"]

ENV PYTHONUNBUFFERED=1