version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  server:
    image: split_learning-split_learning_app
    container_name: split_learning_server
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "server.py"]

  # client1:
  #   image: split_learning-split_learning_app
  #   container_name: split_learning_client1
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["python", "client.py", "--layer_id", "1"]

  # client2:
  #   image: split_learning-split_learning_app
  #   container_name: split_learning_client2
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["python", "client.py", "--layer_id", "2"]
    
volumes:
  rabbitmq_data:
    driver: local